---
output:
  bookdown::pdf_document2:
    toc : no
    keep_tex: no
    number_sections: yes
    extra_dependencies: ["setspace"]
---

<!-- Note this section is Required -->

\doublespacing

The following individuals certify that they have read, and recommend to the Faculty of Graduate
and Postdoctoral Studies for acceptance, the dissertation entitled:

\vspace{5mm}


\noindent\underline{\makebox[6in][l]{Network processes related to political discourse and policy positions: the case of climate change}} 
\noindent\underline{\makebox[6in][l]{policy networks in Canada.}} 

\vspace{2mm}

submitted by \underline{Adam C. Howe} in partial fulfillment of the requirements for

the degree of \noindent\underline{\makebox[5in][l]{Doctor of Philosophy}}  

in \noindent\underline{\makebox[5.8in][l]{Sociology}}

\vspace{5mm}

**Examining Committee:**

\noindent\underline{\makebox[6in][l]{David B. Tindall}}  
Research Supervisor

\noindent\underline{\makebox[6in][l]{Rima Wilkes}}  
Supervisory Committee Member 

\noindent\underline{\makebox[6in][l]{Mark C. J. Stoddart}}  
Supervisory Committee Member 

\noindent\underline{\makebox[6in][l]{John McLevey}}  
Supervisory Committee Member 

\noindent\underline{\makebox[6in][l]{Name of University Examiner}}  
University Examiner

\noindent\underline{\makebox[6in][l]{Name of External Examiner}}  
External Examiner
