---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- Remember, It can't be longer than 350 words! -->
In this dissertation I seek to address the question of how social-structural network processes (such as structural position of network actors, social influence and social selection) are related to political discourses, perceived political influence, and policy positions of network actors, with respect to global climate change in the context of Canadian climate change policy making. I present my findings from a series of analyses that each focus on one aspect of this broader theoretical question. I begin by structurally analyzing five policy networks of climate change policy actors in Canada focusing on subgroup membership and core-periphery structures. The network relations are collaboration, communication, and sharing of scientific information (what I call interaction networks), and perceived influence in domestic climate change policy, and perceived influence on the respondent’s own organization (what I call influence networks). I find that subgroups comprised mainly of research and environmental actors are central within interaction networks, but less central in influence networks. Conversely, groups comprised mainly of business and government actors are less central in interaction networks and highly central in influence networks. I then build on this finding by analyzing how media coverage for environmental actors is associated with their perceived policy influence, conceptualized as the total number of times an actor was nominated by other actors in a policy network as being perceived to be influential. I find a negative association between media coverage and perceived policy influence for activists, but not for environmental movement organizations, challenging established literature that suggests environmental actors who garner more media coverage should be perceived as more influential in policy networks. Then I build on extant research on policy networks that focuses on explaining policy successes and/or failures that often rely on the Advocacy Coalition Framework. I argue this leads to an incomplete understanding of the social dynamics of climate change policy making. I incorporate a policy network analytic approach to show the role micro-structural network processes related to reciprocity, structural equivalence and transitive closure play in giving rise to informal policy networks, along with certain policy beliefs.