---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- Remember, It can't be longer than 150 words! -->
Climate change is serious global problem. Canada has some policies that may help with climate change, but also some that may not. How can we understand this? Making climate change policy involves actors coming together into networks, who interact with each other and judge how influential they think other network actors are. They also have public conversations in the media. I find that research and environmental actors are important in some of the networks, but not seen as very influential. I also find that for environmental actors, media coverage makes them seem less influential. I also look at the beliefs network actors have about climate change policies, and the ways two network actors can be connected. I find some of the policy beliefs actors have are important in explaining the structure of the network, but the specific ways that two network actors can be connected are also important.