---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- This is mandatory! -->

\noindent
This thesis is original work completed by Adam Howe. Guidance was given by the supervisory
committee.

\noindent
For chapter one I was responsible for data cleaning, preparation, and analysis and writing the text. My coauthors originally collected the data, and helped with revisions of the manuscript before publication. This research is covered under the approval from the UBC Behavioural Research Ethics Board under UBC ethics certificate number H12-02465.

\noindent
A version of chapter three was originally published as a research article (Howe, Stoddart, & Tindall, 2020) in the journal Politics and Governance. I was responsible for data cleaning, preparation, and analysis and writing the text. My coauthors originally collected the data, and helped with revisions of the manuscript before publication. This research is covered under the approval from the UBC Behavioural Research Ethics Board under UBC ethics certificate number H12-02465.


>Howe, A. C., Stoddart, M. C. J. J., & Tindall, D. B. (2020). Media Coverage and Perceived Policy Influence of Environmental Actors: Good Strategy or Pyrrhic Victory? Politics and Governance, 8(2), 298. https://doi.org/10.17645/pag.v8i2.2595

\noindent
A version of chapter four was originally published as a research article (Howe, Tindall, & Stoddart, 2020) in the journal Social Networks. I was responsible for data cleaning, preparation, and analysis and writing the text. My coauthors originally collected the data and helped with revisions of the manuscript before publication. This research is covered under the approval from the UBC Behavioural Research Ethics Board under UBC ethics certificate number H12-02465.

>Howe, A. C., Tindall, D. B., & Stoddart, M. C. J. (2020). Drivers of tie formation in the Canadian climate change policy network: Belief homophily and social structural processes. Social Networks.

